import { ALL_PAIRS } from './index'

test('should get all pairs', () => {
  expect(ALL_PAIRS).toStrictEqual([
    'btc_jpy',
    'xrp_jpy',
    'ltc_jpy',
    'eth_jpy',
    'mona_jpy',
    'bcc_jpy',
    'xlm_jpy',
    'qtum_jpy',
    'bat_jpy',
    'omg_jpy',
    'xym_jpy',
    'link_jpy',
    'mkr_jpy',
    'matic_jpy',
    'dot_jpy',
    'doge_jpy',
    'boba_jpy',
    'enj_jpy',
    'astr_jpy',
    'ada_jpy',
    'avax_jpy',
    'axs_jpy',
    'flr_jpy',
    'sand_jpy',
    'gala_jpy',
    'ape_jpy',
    'chz_jpy',
    'oas_jpy',
    'mana_jpy',
  ])
})
